services:
  app:
    build:
      context: ..
      dockerfile: .stacker/Dockerfile
    ports:
    - 80:80
    restart: unless-stopped
    networks:
    - app-network
    labels:
      my.stacker.dns: app
      my.stacker.scope: project
      my.stacker.service: app
networks:
  app-network:
    driver: bridge
